### ISSUE TITLE
Allow importable apps to run even when other apps cannot be imported

### ISSUE THREAD

**Issue by funnell** [papaemmelab/isabl_cli#24]
* isabl_cli version: 0.1.0
* Python version: 3.10.5
* Operating System: Linux

### Description

An example scenario is that someone is developing a new app and has added it to the client settings. Other users will get an error similar to this
```
Failed to import applications: Could not import 'isabl_microbiome_apps.apps.ShotgunPreprocessHuman' for setting 'INSTALLED_APPLICATIONS'. AttributeError: module 'isabl_microbiome_apps.apps' has no attribute 'ShotgunPreprocessHuman'.
```
and then no apps will be available to run from the command line:
```
Usage: isabl [OPTIONS] COMMAND [ARGS]...

  Run Isabl command line tools.

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.

Commands:
  get-bams                   Get storage directories, use `pattern` to...
  get-bed                    Get a BED file for a given Sequencing...
  get-count                  Get count of database instances.
...
```

It would be great to be able to run whichever apps are importable, regardless of the status of any other apps the Isabl instance thinks should be available.

**Comment by juanesarango** [comment]
Since PR #28 is merged, this is allowed now
