### ISSUE TITLE
Improve logging for `process-finished`

### ISSUE THREAD

**Issue by nickp60** [papaemmelab/isabl_cli#33]
* isabl_cli version: 0.1.0
* Python version: 3.11
* Operating System: linux

### Description
I was attempting to move some analyses from FINISHED to SUCCEEDED via the `isabl process-finished` command. [There is logic to ignore](https://github.com/papaemmelab/isabl_cli/blob/master/isabl_cli/commands.py#L85) those tagged with "Processing finished", but no warning shows that these analyses cannot be updated.  It is unclear how these analyses were tagged but not processed

### What I Did
I tried running `isabl process-finished` repeatedly and some anlyses remained in FINISHED state.
<img width="319" alt="Screen Shot 2023-02-02 at 9 21 09 AM" src="https://user-images.githubusercontent.com/14367274/216388363-8be384d0-f5f1-4ce4-87a5-21da6b5439be.png">

### New feature

It would be great either to have a `--force` option to override this behavior or at least a warning to let the user know the issue.

**Comment by juanesarango** [comment]
Thanks @nickp60 for the suggestion. How do you feel about doing a PR for this?

**Comment by nickp60** [comment]
Hi @juanesarango , sure!  Though I will need a bit of assistance with test -- I've had issues getting a full-on dev deployment of isabl running on my machine
