### ISSUE TITLE
Verbose application warnings

### ISSUE THREAD

**Issue by Keimya** [papaemmelab/isabl_cli#42]
### Description

When running "isabl" in terminal, numerous errors are thrown "Failed to import applications:" when applications are not yet installed. Warnings are being printed to stdout instead of stderr.

*possible solution: if applications are not being loaded because they do not exist, capture missing applications and print what the missing apps are and reserve verbose errors for when there are issues with existing applications being found or loaded

**Comment by juanesarango** [comment]
Actually, it used to raise an error when applications were not available to import. And we recently made this change https://github.com/papaemmelab/isabl_cli/issues/24 to allow the cli to work, while only showing a warning. 

Why don't you like the verbose warning? Are you getting it in your analyses stdout logs and would prefer it in stderr logs? I usually fix the import immediately when getting a warning from a missing app. How is your case?

**Comment by funnell** [comment]
Hi @juanesarango that change was really helpful! but sometimes we have times when someone is testing out a new application that is registered in the backend, but not ready in the main branch. In these cases, the persistent warnings can start to get a bit annoying.
For example, if I'm just trying to run `get-metadata` I really don't care if an app couldn't be imported.

However, having these errors sent to stderr would be a good step.

**Comment by juanesarango** [comment]
Ah yeah, you'll get those running other commands. True.

Cool. I merged @Keimya PR #44. Thanks! 🙌🏽

**Comment by Keimya** [comment]
thank you!!
